### PR TITLE
buffer rearrengement + small improvements

### PR DESCRIPTION
**Pull request by ddavlet**
1. Bueffer now allocated for the whole server + deleted in destructor
2. /exit path exits server (for memory leaks testing purposes)
3. max_body_size temporary multiplied by 1024 * 1024

further steps: to-do list + implement streaming body parsing

### CODE REVIEW

**Comment by ddavlet** [comment]
Seems I have to refactor body parsing
even with bigger buffer, browser sends data in a stream
I'll be working on it. It will bring a bit more changes on Server + Request

**Review by lodeme — COMMENTED** [review]
lgtm

added a ticket to support various data types like jpg etc. We can review whether we want this or not, but right now it returns a connection error when trying to upload an image, which seems like undefined behavior

**Review by lodeme — DISMISSED** [review]

**Review by olympiaobr — APPROVED** [review]

**Review by olympiaobr — APPROVED** [review]

**Review by lodeme — COMMENTED** [review]
lgtm

**Review by lodeme — APPROVED** [review]
lgtm

**Review by olympiaobr — APPROVED** [review]

**Pull request merged**
