### PR TITLE
Socket and chunks handling improvements  + minor fix

### PR DESCRIPTION
**Pull request by ddavlet**
Pull request to keep team updated.
Work in progress

Currently multiple requests + chunked requests handling is working.

Further work:
- Detect and configure socket closing points (i.e. error cases)
- Setting request timeout (socket connection timeout)
- Clean up Server::pollLoop() comments and ensure consistent formatting
- Handle created files (proper naming + clean .chunk)

### CODE REVIEW

**Review by olympiaobr — APPROVED** [review]

**Comment by lodeme** [comment]
Chunking looks good and works well. Two observations:

- test and testers folders are now duplicated. We should consolidate them
- why is there a .chunk file remaining after the test?

**Comment by ddavlet** [comment]
@lodeme 
1. One of the folder should be empty. Let figure this out ofter this pull request merge. 

2. "Handle created files (proper naming + clean .chunk)"
This task indicated in pull request message covers changing name and deleting .chunk files. It is just not implemented yet. This pull request just keeps all updated

3.Currently working on resolving merge conflicts, I was just waiting for your answer in Slack

**Comment by ddavlet** [comment]
Merge conflict resolved

**Review by olympiaobr — APPROVED** [review]

**Review by lodeme — APPROVED** [review]
lgtm

**Review by lodeme — APPROVED** [review]

**Pull request merged**
