### PR TITLE
Form file uploads + chunked upload

### PR DESCRIPTION
**Pull request by ddavlet**
Further steps:
1. Check if method is allowed to this path
2. Connect path + folder name (right now it is hard coded)
3. Chunk files cleaning if socket closed and/or limit excided and/or other exceptions
4. Take variables from configuration, rather than constant define
5. Parse form data (if not file(s))

Known issues:
1. Files dropped if directory does not exist
2. Parsing depends on headers with no checks if header exists
3. Form containing data, but not ONLY file(s) is parsed incorrect

### CODE REVIEW

**Review by lodeme — COMMENTED** [review]
There has been a lot here. Maybe it's best if you can talk us through the changes tomorrow morning?

**Comment by ddavlet** [comment]
Pull request conflicts resolved

**Review by olympiaobr — APPROVED** [review]

**Review by lodeme — COMMENTED** [review]
lgtm

**Review by lodeme — APPROVED** [review]
lgtm

**Pull request merged**
